### ISSUE TITLE
crash by debug py with visualstudio_py_debugger 

### ISSUE THREAD

**Issue by ericshenjs** [tht13/Python-vscode#15] opened 2016-03-25 02:02 UTC
crash by debug py with visualstudio_py_debugger 

![Uploading visualstudio_py_debugger.JPG…]()

**Comment by ericshenjs** [comment] 2016-03-25 02:03
![Uploading visualstudio_py_debugger.JPG…]()
![Uploading visualstudio_py_debugger.JPG…]()

**Comment by ericshenjs** [comment] 2016-03-25 02:45
![Uploading visualstudio_py_debugger.JPG…]()

**Comment by ericshenjs** [comment] 2016-03-25 02:45
Traceback (most recent call last):
  File "C:\Users\ADMINI~1\AppData\Local\Temp\tmp-9652p3NPXf27X8ld\visualstudio_py_debugger.py", line 1646, in loop
    cmd()
  File "C:\Users\ADMINI~1\AppData\Local\Temp\tmp-9652p3NPXf27X8ld\visualstudio_py_debugger.py", line 1918, in command_execute_code
    thread.run_on_thread(text, cur_frame, eid, frame_kind, repr_kind)
  File "C:\Users\ADMINI~1\AppData\Local\Temp\tmp-9652p3NPXf27X8ld\visualstudio_py_debugger.py", line 1246, in run_on_thread
    self.schedule_work(lambda : self.run_locally(text, cur_frame, execution_id, frame_kind, repr_kind))
  File "C:\Users\ADMINI~1\AppData\Local\Temp\tmp-9652p3NPXf27X8ld\visualstudio_py_debugger.py", line 1238, in schedule_work
    self.unblock()
  File "C:\Users\ADMINI~1\AppData\Local\Temp\tmp-9652p3NPXf27X8ld\visualstudio_py_debugger.py", line 1234, in unblock
    self._block_lock.release()
RuntimeError: release unlocked lock

**Comment by tht13** [comment] 2016-03-25 10:33
I am closing this issue because of the following reasons.

1. There is no debugger in this extenstion
2. The traceback puts all .the files in the Temp directory which neither my extension
    nor Visual Studio Code use
3.  The issue is not described well at all and it appears the images you uploaded have failed.

**Closed by tht13** 2016-03-25 10:33 UTC
